# pubspec.yaml
name: my_flet_app
description: A Flet app.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flet:
    git:
      url: https://github.com/flet-dev/flet
      ref: stable

  # 明确锁定版本，避免拉取过高版本
  webview_flutter: 4.7.0

# 强制所有子包使用 4.7.0，解决语言版本 3.9 错误
dependency_overrides:
  webview_flutter_android: 4.7.0
  webview_flutter_ios: 4.7.0

flutter:
  uses-material-design: true