# pubspec.yaml
name: my_flet_app
description: A Flet app.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flet:
    git:
      url: https://github.com/flet-dev/flet
      ref: stable  # 推荐改为具体稳定 commit 或 tag，避免拉到新版本

  # 明确指定兼容版本，并覆盖所有子包
  webview_flutter: 4.7.0

  # 强制所有 webview_flutter 的平台实现也使用 4.7.0
dependency_overrides:
  webview_flutter_android: 4.7.0
  webview_flutter_ios: 4.7.0
  webview_flutter_linux: 4.7.0
  webview_flutter_macos: 4.7.0
  webview_flutter_wkwebview: 4.7.0

flutter:
  uses-material-design: true